version: "3.9"
   
services:
  db:
    build: ./db
    #volumes:
    # - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-0dzsg5sv1g)za-$m84ljv64ar@qfrpk@#z_neh^#&e5%tfw_n1
      - DEBUG=1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
        
      
