# Generated by Django 3.2 on 2021-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('overall', models.SmallIntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('wage', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=3, null=True)),
                ('release_clause', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': True,
            },
        ),
    ]
