# Generated by Django 3.2 on 2021-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210411_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_exists',
            field=models.BooleanField(default=True),
        ),
    ]
